# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-14 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='pub_date',
            new_name='org_date',
        ),
    ]
