# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-14 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0002_auto_20161014_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='count',
        ),
    ]
